### ISSUE TITLE
says api token is invalid

### ISSUE THREAD

**Issue by bipulbhattarai** [MoonCactus/scaleway_remote_backup#2]
API token is invalid, even the token is correct, by token it means API token right not , sceret key

**Comment by MoonCactus** [comment]
Most probably, either your API is invalid or you provided the wrong part of the key :)
It should look like `97f7e45d-ff5b-d8a8-f79a-04e3e143992f` for example.

**Comment by MoonCactus** [comment]
OK, most probably not-a-bug.
Please if you submit an issue, answer to the replies ;)
